version: '3'

services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 3.0.3
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - .:/railsapp:cached
