version: '3'

services:
  app:
    build:
      context: .
      args:
        RUBY_VERSION: 3.0.3
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - .:/railsapp:cached
    environment:
      CHROME_URL: http://chrome:3333

  chrome:
    image: browserless/chrome:1-chrome-stable
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: 600000
