name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test with Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        ruby_version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'

    steps:
      - uses: actions/checkout@v3

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Gem cache
        uses: actions/cache@v3
        with:
          path: ~/gems
          key: ${{ matrix.ruby_version }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ matrix.ruby_version }}-gems-

      - name: Bundle
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3

      - name: Setup
        run: bin/rails db:setup

      - name: Run tests
        run: bin/rails test

  system-test:
    name: System Test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          docker-compose up -d
          docker-compose exec -T app rails test:system

