name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test with Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        ruby_version:
          - 2.7
          - 3.0

    steps:
      - uses: actions/checkout@v2

      - name: Create a symlink for libffi.so.6 to fix LoadError on `rails db:setup`
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Gem cache
        uses: actions/cache@v2
        with:
          path: ~/gems
          key: ${{ matrix.ruby_version }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ matrix.ruby_version }}-gems-

      - name: Bundle
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3

      - name: Setup
        run: bin/rails webpacker:install db:setup

      - name: Run tests
        run: bin/rails test
